(* Generate one of two chapter-listing files from
   Manual/Description/chapters.txt:

     gen_chap_lists summary       > SUMMARY.md
     gen_chap_lists latex-include > chapters-include.tex

   chapters.txt is a human-maintained list of chapter stems, one
   per line, ignoring blank lines and `#` comments.  For each
   stem in order:

     - SUMMARY.md emits a top-level entry only when <stem>.smd
       exists (those are the chapters with a mdbook
       presentation).  The entry's title is the H1 of the .smd;
       sub-entries are draft-chapter links built from the H2
       headings.
     - chapters-include.tex emits `\include{<stem>}` for every
       stem unconditionally (the LaTeX bundle uses .tex from
       .smd, .stex, or hand-maintained sources interchangeably).

   The script must be run from Manual/Description/ (paths are
   relative). *)

(* --- file-system helpers --------------------------------------- *)

fun readFile path =
    let val s = TextIO.openIn path
        val all = TextIO.inputAll s
        val () = TextIO.closeIn s
    in all end

fun fileExists path =
    OS.FileSys.access (path, [OS.FileSys.A_READ])

fun emit s = TextIO.output (TextIO.stdOut, s)

fun die msg =
    ( TextIO.output (TextIO.stdErr, msg ^ "\n")
    ; OS.Process.exit OS.Process.failure )

(* --- chapters.txt parser --------------------------------------- *)

fun trim s =
    let val ss = Substring.full s
        val ss = Substring.dropl Char.isSpace ss
        val ss = Substring.dropr Char.isSpace ss
    in Substring.string ss end

fun parseChaptersFile path =
    let
      val all = readFile path
      val lines = String.fields (fn c => c = #"\n") all
      fun keep ln =
          let val t = trim ln
          in t <> "" andalso not (String.isPrefix "#" t) end
    in
      List.map trim (List.filter keep lines)
    end

(* --- .smd H1/H2/H3 extraction ---------------------------------- *)

fun smdLines stem =
    let val all = readFile (stem ^ ".smd")
        val ls = String.fields (fn c => c = #"\n") all
    in case List.rev ls of
           "" :: rest => List.rev rest
         | _ => ls
    end

fun isHeading pre s =
    String.isPrefix pre s andalso
    (size s = size pre orelse String.sub (s, size pre) <> #"#")

fun stripPrefix pre s = trim (String.extract (s, size pre, NONE))

(* Backticks in headings (e.g. `## The Theory `min``) are dropped
   so the slug-rewriting JS in theme/index.hbs sees a plain title. *)
fun cleanTitle s =
    String.translate (fn #"`" => "" | c => str c) s

fun extractH1 ls =
    let fun go [] = NONE
          | go (l :: rest) =
            if isHeading "# " l
            then SOME (cleanTitle (stripPrefix "# " l))
            else go rest
    in go ls end

(* Walk lines tracking the current H2; return one entry per H2 with
   its list of H3 titles in source order.  H3s appearing before the
   first H2 are silently dropped (well-structured chapters don't
   have these). *)
fun extractSections ls =
    let
      fun close (NONE, _, acc) = acc
        | close (SOME h2, h3s, acc) = (h2, List.rev h3s) :: acc
      fun go [] curH2 curH3s acc =
            List.rev (close (curH2, curH3s, acc))
        | go (l :: rest) curH2 curH3s acc =
            if isHeading "## " l then
              let val t = cleanTitle (stripPrefix "## " l)
                  val acc' = close (curH2, curH3s, acc)
              in go rest (SOME t) [] acc' end
            else if isHeading "### " l then
              (case curH2 of
                   NONE => go rest curH2 curH3s acc
                 | SOME _ =>
                     let val t = cleanTitle (stripPrefix "### " l)
                     in go rest curH2 (t :: curH3s) acc end)
            else go rest curH2 curH3s acc
    in go ls NONE [] [] end

(* --- SUMMARY.md output ----------------------------------------- *)

fun emitSummary stems =
    let
      fun emitH3 t = emit ("    - [" ^ t ^ "]()\n")
      fun emitH2 (h2, h3s) =
          ( emit ("  - [" ^ h2 ^ "]()\n")
          ; List.app emitH3 h3s )
      fun emitChap stem =
          if not (fileExists (stem ^ ".smd")) then ()
          else let
            val ls = smdLines stem
            val title = case extractH1 ls of
                            SOME t => t
                          | NONE => die ("No H1 in " ^ stem ^ ".smd")
          in
            emit ("- [" ^ title ^ "](" ^ stem ^ ".smd)\n");
            List.app emitH2 (extractSections ls)
          end
    in
      emit "# Summary\n\n# The HOL System\n\n";
      List.app emitChap stems
    end

(* --- chapters-include.tex output ------------------------------- *)

fun emitLatexInclude stems =
    ( emit "% Generated by Manual/Tools/gen_chap_lists from\n";
      emit "% Manual/Description/chapters.txt; do not edit by hand.\n";
      List.app (fn s => emit ("\\include{" ^ s ^ "}\n")) stems )

(* --- entry point ----------------------------------------------- *)

fun main () =
    let val stems = parseChaptersFile "chapters.txt"
    in case CommandLine.arguments () of
           ["summary"]       => emitSummary stems
         | ["latex-include"] => emitLatexInclude stems
         | _ => die "usage: gen_chap_lists summary | latex-include"
    end
