(* mipsLib - generated by L<3> - Thu Jan 23 13:44:48 2014 *)
structure mipsLib :> mipsLib =
struct
open HolKernel boolLib bossLib
open utilsLib mipsTheory
val () = (numLib.temp_prefer_num (); wordsLib.prefer_word ())
fun mips_compset thms =
   utilsLib.theory_compset (thms, mipsTheory.inventory)
end
