#!/bin/bash
HOLDIR=`pwd`
echo Cleaning mlyacc library code
cd ${HOLDIR}/tools/mlyacc/mlyacclib
${HOLDIR}/bin/Holmake cleanAll
echo Cleaning examples/machine-code
cd ${HOLDIR}/examples/machine-code
./cleanall
cd ${HOLDIR}/examples/miller
echo Cleaning examples/miller
./cleanall
cd ${HOLDIR}
