signature HOLSourcePrinter = sig

type printer = {token: string -> unit, startSpan: int * int -> unit, stopSpan: unit -> unit}
val mkPrinter: (int -> int) ->
  {str: string -> unit, startSpan: int * int -> unit, stopSpan: unit -> unit} -> printer

val printDec: (int * int -> string -> unit) -> HOLSourceAST.dec -> printer -> unit
val printDecs: (int * int -> string -> unit) -> HOLSourceAST.dec list -> printer -> unit

end

(* ----------------------------------------------------------------------
    Overview
   ----------------------------------------------------------------------

    HOLSourcePrinter walks a HOLSourceAST.dec and emits the
    corresponding SML source text via a token-stream interface.  In
    the standard pipeline its input is the result of
    HOLSourceExpand.expandDec, so the HOL-specific surface forms have
    already been rewritten to plain SML; the printer's job is then to
    serialise the expansion back out while preserving enough source-
    position information that downstream compilers can blame errors on
    the original .sml file.

    The token-stream interface.  A printer is

      {token : string -> unit,
       startSpan : int * int -> unit,
       stopSpan : unit -> unit}

    Every visible token is emitted via `token` (which appends a single
    trailing space, so the output is always whitespace-separated).
    Around each AST node the printer brackets the output with
    startSpan / stopSpan calls naming the node's source extent.
    Consumers can use these hooks to intersperse line directives,
    syntax highlighting, or coverage annotations.

    mkPrinter glues this token-stream interface to a raw sink.  Given

      mkLine : int -> int       (* offset -> line number *)
      {str, startSpan, stopSpan}

    it returns a printer whose token function delegates to str (with
    the trailing space) and whose startSpan inserts as many "\n"
    characters as needed to bring the output's current line number up
    to the line of the incoming span.  The newlines are emitted as a
    Word8Vector of 0x0A bytes via str, so encoding stays consistent
    with the underlying byte sink.  This is what lets the printer
    reproduce the original line layout: as long as mkLine reports
    truthful line numbers (typically `#line o fileline` from the AST's
    event log), the printed text re-aligns to the source line breaks.

    Public entry points.  Both take an error-sink callback for the
    diagnostics emitted by the AST itself (e.g. when printing
    DecBad / ExpBad nodes that originated in malformed input):

      - printDec  errSink dec  printer
      - printDecs errSink decs printer

    Internally the printer walks the AST with a small grove of mutually
    recursive printers, one per sort: printTy, printTyBind, printConBind,
    printDatBind, printExBind, printExp, printRow, printDec, printSigExp,
    printStrExp, printQDecl, etc.  Helpers worth noting:

      - spanned : (int * int) -> ('printer -> 'a) -> 'printer -> 'a
        Wraps an inner printing action with startSpan / stopSpan
        bracketing.  Every node-level printer goes through this so the
        consumer always sees balanced open/close events.
      - parenIf : adds parentheses when the surrounding precedence
        requires them; mirrors the precedence handling done by the
        parser when it built the tree.
      - separated / separatedBar : print a list with an explicit
        separator token (",", ";", "*", "and", "|" with a leading
        bar prefix); used for tuples, records, datbind chains, fn /
        case arms, etc.
      - seq : prints an 'a seq -- the Empty / One / Many ParenWrapping
        idiom from the AST, parenthesising and comma-separating Many.
      - otoken : emits a string only when an int option position is
        present; used for the right-bracket / closer tokens whose
        absence means the parser saw a missing closer in the source
        and wants the printer not to invent one.

    DecExpansion is printed by emitting `result` while keeping the
    span markers from `orig`.  This means line directives generated by
    consumers downstream (e.g. mlton-compatible #line pragmas) point
    at the original surface text even though what is emitted is the
    expanded SML.  DecBad and other error nodes print a placeholder
    token (e.g. "bad") rather than failing; combined with the
    error-sink callback, the printer is best-effort and never aborts
    the stream.
   ---------------------------------------------------------------------- *)
