###############################################################################
#  Makefile interface to Holmake
#  Created by Joe Hurd, June 2002
###############################################################################

HOLMAKE = Holmake

.PHONY: all
all:
	$(HOLMAKE) --qof

.PHONY: clean
clean:
	$(HOLMAKE) cleanAll

.PHONY: world
world: clean all
