(* armLib - generated by L<3> - Thu Jun 27 15:43:42 2013 *)
structure armLib :> armLib =
struct

open HolKernel boolLib bossLib
open utilsLib armTheory

val () = (numLib.temp_prefer_num (); wordsLib.prefer_word ())

fun arm_compset thms =
   utilsLib.theory_compset (thms, armTheory.inventory)

end
