(* armLib - generated by L<3> - Thu Mar 28 13:10:25 2013 *)
structure armLib :> armLib =
struct

open HolKernel boolLib bossLib
open utilsLib armTheory

val () = (numLib.prefer_num (); wordsLib.prefer_word ())

fun arm_compset thms =
   utilsLib.theory_compset (thms, armTheory.inventory)

end
