world:
	pdflatex presentation.tex
	pdflatex presentation.tex
	pdflatex ds.tex
	bibtex ds
	pdflatex ds.tex
	pdflatex ds.tex

clean:
	rm -f *.ps *~ *.dvi *.aux *.log *.idx *.toc *.nav *.out *.snm *.flc *.vrb
