#!/bin/sh

if [ $# -eq 0 ]
then
        echo "Usage: $0 dir1 dir2 .. dirn" >&2
        exit 1
fi

# assumes recent GNU grep
grep -n -R -P "[\x80-\xFF]" --include=*.sml --include=*.sig --exclude=*Theory.sig "$@"
