#!/bin/bash

# assumes a particular flavour of grep, as per http://stackoverflow.com/questions/3001177/how-do-i-grep-for-all-non-ascii-characters-in-unix

# As of 18 Feb 2014, sources include some Unicode in comments.

LC_ALL=C grep -R -n -v -E '^[[:print:][:space:]]*$|UOK' --include=*.sml --exclude=*Theory.sml --exclude=*Theory.sig --exclude selftest.sml --exclude EmitTeX.sml "$(dirname $0)/../src/"
