(* Scanner.sig *)

(* generic signature SCANNER of Scanners generated by LexGen.main.
 * requires that environment provide a structure Token containing
 * type token *)

signature SCANNER = 
sig
  val makeLex : Token.token LexBuffer.lexbuf -> unit -> Token.token
end
