(* m0Lib - generated by L<3> - Mon Jul 08 14:02:44 2013 *)
structure m0Lib :> m0Lib =
struct

open HolKernel boolLib bossLib
open utilsLib m0Theory

val () = (numLib.temp_prefer_num (); wordsLib.prefer_word ())

fun m0_compset thms =
   utilsLib.theory_compset (thms, m0Theory.inventory)

end
