val () = Feedback.emit_WARNING := false;
val () = ProofTraceReplay.print_statistics := true

(*
open OS.FileSys
val () = List.app (fn f => if access(f^"Theory.tr.gz", [A_READ]) then () else print(f^" "))
*)
val () = ProofTraceReplay.replay_sequence
  [(* HOL4 base theories *)
   "bool", "marker", "num", "sat", "combin",
   "relation", "prim_rec", "quotient", "pair",
   "arithmetic", "numeral", "cv", "numpair",
   "ind_type", "one", "sum", "option", "While",
   "reduce", "divides", "normalForms", "pred_set",
   "basicSize", "list", "rich_list", "sorting",
   "finite_map", "alist", "indexedLists", "logroot",
   "sptree", "permutes", "iterate", "fcp", "bit",
   "ternaryComparisons", "string", "numposrep",
   "ASCIInumbers", "sum_num", "numeral_bit", "words",
   "set_sep", "byte", "bitstring", "set_relation",
   "llist", "poset", "fixedPoint", "path", "alignment",
   "address", "bag", "toto", "comparison",
   "mergesort", "normalizer", "gcd",
   "integer", "int_arith", "cooper", "Omega", "integer_word",
   "hrat", "hreal", "realax", "real_arith", "real", "intreal",
   "intExtension", "intReduce", "frac", "primeFactor", "rat", 
   "blast", "multiword", "tailrec", "mc_multiword",
   "binary_ieee", "machine_ieee",
   "location",
   "quantHeuristics", "ConseqConv", "patternMatches",
   "balanced_map", "res_quan", "int_bitwise",
   "container", "state_transformer", "errorMonad", "errorLogMonad",
   "alist_tree", "transfer", "spt_closure",
   "lprefix_lub", "grammar", "peg", "pegexec",
   "charset", "vec_map", "oset",
   "FormalLang", "regexp", "regexp_map", "regexp_compiler",
   "simpleSexp",
   (* CakeML theories *)
   "ag32",
   "misc",
   "Marshalling",
   "backendProps",
   "backend_common",
   "db_vars",
   "gc_shared",
   "copying_gc",
   "gen_gc",
   "gen_gc_partial",
   "mllist",
   "mlmap",
   "mloption",
   "mlset",
   "mlstring",
   "cfFFIType",
   "ffi",
   "mlint",
   "jsonLang",
   "mlrat",
   "mlsexp",
   "displayLang",
   "mlvector",
   "export",
   "export_ag32",
   "export_arm7",
   "export_arm8",
   "export_mips",
   "export_riscv",
   "export_x64",
   "mlprettyprinter",
   "namespace",
   "ast",
   "asm",
   "asmSem",
   "asmProps",
   "arm",
   "arm_step",
   "arm7_target",
   "arm8",
   "arm8_step",
   "arm8_target",
   "ag32_target",
   "crepLang",
   "crep_arith",
   "crep_inline",
   "flatLang",
   "flat_elim",
   "fpSem",
   "closLang",
   "bvi",
   "bvi_let",
   "bvi_tailrec",
   "bvl",
   "bvl_const",
   "bvl_handle",
   "bvl_inline",
   "bvl_jump",
   "clos_annotate",
   "clos_call",
   "clos_fvs",
   "clos_interp",
   "clos_letop",
   "clos_mti",
   "clos_number",
   "clos_op",
   "clos_ticks",
   "clos_known",
   "clos_to_bvl",
   "dataLang",
   "bvl_to_bvi",
   "data_live",
   "data_simp",
   "data_space",
   "bvi_to_data",
   "flat_to_clos",
   "fromSexp",
   "labLang",
   "lab_filter",
   "lab_to_target",
   "loopLang",
   "loop_call",
   "loop_live",
   "crep_to_loop",
   "loop_remove",
   "mips_target",
   "namespaceProps",
   "panLang",
   "panLexer",
   "panPEG",
   "panPtreeConversion",
   "panStatic",
   "pan_common",
   "pan_globals",
   "pan_simp",
   "pan_to_crep",
   "parmove",
   "pattern_common",
   "riscv_target",
   "semanticPrimitives",
   "evaluate",
   "ml_monadBase",
   "pattern_semantics",
   "pattern_comp",
   "flat_pattern",
   "reg_alloc",
   "linear_scan",
   "reg_allocProof",
   "linear_scanProof",
   "semanticPrimitivesProps",
   "closSem",
   "bvlSem",
   "bviSem",
   "bvlProps",
   "bviProps",
   "bvi_letProof",
   "bvi_tailrecProof",
   "bvl_constProof",
   "bvl_handleProof",
   "bvl_inlineProof",
   "bvl_jumpProof",
   "bvl_to_bviProof",
   "closProps",
   "clos_annotateProof",
   "clos_callProof",
   "clos_constantProof",
   "clos_fvsProof",
   "clos_interpProof",
   "clos_knownProps",
   "clos_letopProof",
   "clos_mtiProof",
   "clos_numberProof",
   "clos_opProof",
   "clos_ticksProof",
   "clos_knownProof",
   "clos_to_bvlProof",
   "evaluateProps",
   "evaluate_dec",
   "flatSem",
   "flatProps",
   "flat_elimProof",
   "flat_patternProof",
   "flat_to_closProof",
   "source_let",
   "source_to_flat",
   "source_to_source",
   "stackLang",
   "stack_names",
   "stack_remove",
   "tokens",
   "gram",
   "gramProps",
   "cmlNTProps",
   "lexer_fun",
   "lexer_impl",
   "tokenUtils",
   "cmlPEG",
   "cmlPtreeConversion",
   "cmlParse",
   "pegSound",
   "pegComplete",
   "typeSystem",
   "infer_t",
   "primTypes",
   "semantics",
   "source_evalProof",
   "source_letProof",
   "source_to_flatProof",
   "source_to_sourceProof",
   "typeSoundInvariants",
   "typeSysProps",
   "primSemEnv",
   "ml_prog",
   "cfHeapsBase",
   "cfHeaps",
   "clFFI",
   "fsFFI",
   "fsFFIProps",
   "ml_translator",
   "cfStore",
   "cfNormalise",
   "cfApp",
   "cf",
   "cfLetAuto",
   "ml_pmatch",
   "cfMain",
   "ml_monad_translatorBase",
   "ml_monad_translator",
   "cfMonad",
   "runtimeFFI",
   "std_prelude",
   "cfDiv",
   "RuntimeProg",
   "OptionProg",
   "ListProg",
   "RuntimeProof",
   "VectorProg",
   "StringProg",
   "mlbasicsProg",
   "IntProg",
   "PrettyPrinterProg",
   "RatProg",
   "CharProg",
   "Word64Prog",
   "Word8Prog",
   "Word8ArrayProg",
   "ArrayProg",
   "MapProg",
   "SetProg",
   "HashtableProg",
   "CommandLineProg",
   "DoubleProg",
   "Word8ArrayProof",
   "CommandLineProof",
   "MarshallingProg",
   "TextIOProg",
   "TextIOProof",
   "SexpProg",
   "basisProg",
   "unify",
   "infer",
   "inferProps",
   "envRel",
   "infer_eComplete",
   "infer_eSound",
   "type_dCanon",
   "type_eDeterm",
   "inferComplete",
   "inferSound",
   "weakening",
   "typeSound",
   "semanticsProps",
   "wordLang",
   "loop_to_word",
   "pan_to_word",
   "presLang",
   "wordConvs",
   "wordSem",
   "stackSem",
   "stackProps",
   "stack_namesProof",
   "stack_removeProof",
   "targetSem",
   "labSem",
   "labProps",
   "lab_filterProof",
   "targetProps",
   "lab_to_targetProof",
   "wordProps",
   "word_alloc",
   "word_allocProof",
   "word_bignum",
   "word_bignumProof",
   "word_copy",
   "word_copyProof",
   "word_cse",
   "word_depth",
   "word_depthProof",
   "word_elim",
   "word_elimProof",
   "word_inst",
   "word_instProof",
   "word_remove",
   "word_removeProof",
   "word_simp",
   "word_cseProof",
   "word_simpProof",
   "word_to_stack",
   "word_to_stackProof",
   "word_unreach",
   "word_to_word",
   "data_to_word",
   "dataSem",
   "dataProps",
   "data_liveProof",
   "data_simpProof",
   "data_spaceProof",
   "bvi_to_dataProof",
   "gc_combined",
   "stack_alloc",
   "stack_rawcall",
   "stack_rawcallProof",
   "stack_to_lab",
   "backend",
   "ag32_config",
   "arm7_config",
   "arm8_config",
   "backend_passes",
   "mips_config",
   "pan_to_target",
   "pan_passes",
   "riscv_config",
   "wordConvsProof",
   "word_gcFunctions",
   "data_to_word_memoryProof",
   "data_to_word_gcProof",
   "data_to_word_bignumProof",
   "data_to_word_assignProof",
   "stack_allocProof",
   "stack_to_labProof",
   "word_unreachProof",
   "word_to_wordProof",
   "data_to_wordProof",
   "backendProof",
   "x64_target",
   "x64_config",
   "compiler",
   "compilerProof"]

val (named, _) = ProofTraceReplay.replayed_thms "compilerProof"
val th = Redblackmap.find(named, "compile_correct")
val () = print "concl:\n"

open Type Term Thm

fun print_ty ty =
  if is_vartype ty then dest_vartype ty
  else let
    val (opn, args) = dest_type ty
    val args = List.map print_ty args
  in if List.null args then opn
     else String.concat["(", String.concatWith "," args, ") ", opn]
  end

fun print_tm tm =
  if is_var tm then let
    val (x,ty) = dest_var tm
  in String.concat[x,":",print_ty ty] end
  else if is_const tm then let
    val (x,ty) = dest_const tm
  in x end
  else if is_abs tm then let
    val (x,b) = dest_abs tm
  in String.concat["(\\", print_tm x, ". ", print_tm b, ")"] end
  else let val (f,x) = dest_comb tm in
    String.concat["(", print_tm f, " ", print_tm x, ")"]
  end

val () = print (print_tm (concl th))
val () = print "\nNumber of hyps: "
val () = print (Int.toString (List.length (hyp th)))
val () = print "\nTags: "
val (tag, axs) = Tag.dest_tag(Thm.tag th)
val () = print (String.concatWith ","  tag)
val () = print "\nAxioms: "
val () = print (String.concatWith "," axs)
val () = print "\n" 
