val _ = PolyML.use (OS.Path.concat(Globals.HOLDIR, "tools-poly/holinteractive.ML"));
val () = qload "ProofTraceReplay";
val () = Feedback.emit_WARNING := false;
val () = ProofTraceReplay.print_statistics := true

val seq = ["bool", "marker", "num", "sat", "combin",
           "relation", "prim_rec", "quotient", "pair",
           "arithmetic", "numeral", "cv", "numpair",
           "ind_type", "one", "sum", "option", "While",
           "reduce", "divides", "normalForms", "pred_set",
           "basicSize", "list", "rich_list", "sorting",
           "finite_map", "alist", "indexedLists", "logroot",
           "sptree", "permutes", "iterate", "fcp", "bit",
           "ternaryComparisons", "string", "numposrep",
           "ASCIInumbers", "sum_num", "numeral_bit", "words",
           "set_sep", "byte", "bitstring", "set_relation",
           "llist", "poset", "fixedPoint", "path", "alignment",
           "address", "bag", "misc", "toto", "comparison",
           "mergesort", "mllist", "mlstring", "normalizer", "gcd",
           "integer", "int_arith", "cooper", "Omega", "integer_word",
           "hrat", "hreal", "realax", "real_arith", "real", "intreal",
           "blast", "multiword", "tailrec", "mc_multiword",
           "binary_ieee", "machine_ieee", "namespace", "location",
           "quantHeuristics", "ConseqConv", "patternMatches",
           "balanced_map", "ast", "asm", "ffi", "lprefix_lub", "fpSem",
           "semanticPrimitives", "ml_monadBase", "backend_common",
           "namespaceProps", "semanticPrimitivesProps", "backendProps",
           "reg_alloc", "linear_scan", "db_vars",
           "flatLang", "closLang", "stackLang", "dataLang", "wordLang", "bvl",
           "clos_op", "clos_letop", "clos_ticks",
           "clos_fvs", "clos_known", "clos_annotate", "clos_call",
           "clos_number", "clos_mti", "bvl_jump", "clos_to_bvl",
           "word_depth", "data_space",
           "word_bignum",
           "wordConvs",
           "word_alloc", "word_remove", "word_unreach",
           "word_inst", "word_copy", "word_cse", "word_simp",
           "word_to_word",
           "data_to_word",
           "wordSem", "wordProps",
           "closSem", "bvlSem",
           "dataSem", "dataProps",
           "word_bignumProof", "word_simpProof",
           "reg_allocProof", "linear_scanProof",
           "data_spaceProof",
           "data_to_word_memoryProof",
           "data_to_word_bignumProof",
           "word_allocProof",
           "wordConvsProof", "word_unreachProof", "word_cseProof",
           "word_instProof", "word_copyProof", "word_removeProof",
           "word_to_wordProof"]

val () = ProofTraceReplay.replay_sequence seq
