#! /bin/sh -x
#
# Shell script to modify the .doc files in <dir>
# directory by replacing the word size with "<n>"
#
#	/bin/sh wordn-doc <sed> <dir>
#
for file in `ls -1 $2/*.doc`
     do
       sed -f $1 "$file" > "$file"2
       mv -f "$file"2 "$file"
     done
