structure Systeml :> Systeml = struct

(* This is the UNIX implementation of the Systeml functionality.  It is the
   very first thing compiled by the HOL build process so it absolutely
   can not depend on any other HOL source code. *)

structure Path = OS.Path
structure Process = OS.Process
structure FileSys = OS.FileSys

local
  open Process
  fun concat_wspaces munge strl = String.concatWith " " (map munge strl)
in

  val unix_meta_chars = [#"'", #"\"", #"|", #" ", #">", #"\t", #"\n", #"<",
                         #"\\", #"#"]
  fun is_meta c = List.exists (fn y => c = y) unix_meta_chars
  fun is_meta_string(s,i) = if i >= size s then false
                            else if is_meta (String.sub(s,i)) then true
                            else is_meta_string(s, i + 1)
  fun unix_trans c = if is_meta c then "\\" ^ str c else str c

  fun protect s = if is_meta_string(s,0) then String.translate unix_trans s
                  else s

  val systeml = system o concat_wspaces protect

  fun systeml_out {outfile} c =
    system (concat_wspaces protect c ^ " > " ^ protect outfile ^ " 2>&1")

  val system_ps = Process.system
  (* see winNT-systeml.sml for an explanation of why what is a synonym under
     unix needs to be slightly different on Windows. *)

  (* would like to be using Posix.Process.exec, but this seems flakey on
     various machines (and is entirely unavailable on Moscow ML) *)
  fun exec (comm, args) = OS.Process.exit (systeml (comm::tl args))

  fun get_first f [] = NONE
    | get_first f (h::t) = case f h of NONE => get_first f t
                                     | x => x


  fun find_my_path () = let
    (* assumes directory hasn't been changed yet *)
    val myname = CommandLine.name()
    val {dir,file} = Path.splitDirFile myname
  in
    if dir = "" then let
        val pathdirs = String.tokens (fn c => c = #":")
                                     (valOf (Process.getEnv "PATH"))
        open FileSys
        fun checkdir d = let
          val f = Path.concat(d,file)
        in
          if access(f, [A_READ, A_EXEC]) then SOME f else NONE
        end
      in
        valOf (get_first checkdir pathdirs)
      end
    else
      Path.mkAbsolute {path = myname,relativeTo = FileSys.getDir()}
  end

  fun xable_string s = s

  fun mk_xable file =
    let
      val r = systeml ["chmod", "a+x", file]
    in
      if Process.isSuccess r then r
      else if FileSys.access (file,[FileSys.A_EXEC]) then
          (* if we can execute it, then continue with a warning *)
          (* NB: MoSML docs say FileSys.access uses real uid/gid, not effective uid/gid,
             so this test may be bogus if we are setuid.  This is unlikely(!). *)
          (print ("Non-fatal warning: couldn't set world execute permission on "^file^",\n  but continuing anyway since at least the current user has execute permission.\n");
           OS.Process.success)
      else (print ("unable to set execute permission on "^file^".\n");
            OS.Process.failure)
    end


fun normPath s = Path.toString(Path.fromString s)

fun fullPath slist =
    normPath (List.foldl (fn (p1,p2) => Path.concat(p2,p1))
                         (hd slist) (tl slist))


(* these values are filled in by configure.sml *)
val HOLDIR = ""
val MOSMLDIR = ""
val OS = ""
val POLY = ""
val POLYC = ""
val POLY_VERSION = 0
val POLYMLLIBDIR = ""
val POLY_LDFLAGS = []
val POLY_LDFLAGS_STATIC = []
val CC = ""

val DEPDIR = ".hol/make-deps"
val LOGDIR = ".hol/logs"
val GNUMAKE = ""
val DYNLIB = ""
val version = ""
val ML_SYSNAME = ""
val release = ""
val DOT_PATH = ""
val MV = ""
val CP = ""
val DEFAULT_STATE = fullPath [HOLDIR, "bin", "hol.state"]

val isUnix = true
val haveWord64 = false
local val cast : 'a -> int = Obj.magic
in
  fun pointer_eq (x:'a, y:'a) = (cast x = cast y)
end

val build_log_dir = fullPath [HOLDIR, "tools", "build-logs"]
val build_log_file = fullPath [build_log_dir, "current-build-log"]
val make_log_file = "current-make-log"
val build_after_reloc_envvar = "HOL_REBUILD_HEAPS_ONLY"


(* Generate unified HOL shell script supporting --bare and --noquote flags.
   By default uses unquote filter; --noquote disables it. *)
fun emit_hol_script target {boss_qend, bare_qend} = let
  val ostrm = TextIO.openOut target
  fun output s = TextIO.output(ostrm, s)
  val qfilter = protect (fullPath [HOLDIR, "bin", "unquote"])
  val sigobj = protect (fullPath [HOLDIR, "sigobj"])
  val std_prelude = protect (fullPath [HOLDIR, "tools", "std.prelude"])
  val mosml = protect (fullPath [MOSMLDIR, "mosml"])
  val qinit = protect (fullPath [HOLDIR, "tools", "unquote-init.sml"])
in
  output "#!/bin/sh\n";
  output "# The HOL script\n";
  output "# (automatically generated by HOL configuration)\n\n";
  output "# Parse --bare and --noquote flags\n";
  output "BARE=0\n";
  output "NOQUOTE=0\n";
  output "ARGS=\"\"\n";
  output "for arg in \"$@\"; do\n";
  output "  case \"$arg\" in\n";
  output "    --bare) BARE=1 ;;\n";
  output "    --noquote) NOQUOTE=1 ;;\n";
  output "    *) ARGS=\"$ARGS $arg\" ;;\n";
  output "  esac\n";
  output "done\n\n";
  output "# Select end script based on --bare\n";
  output "if [ $BARE -eq 1 ]; then\n";
  output ("  QEND=" ^ protect bare_qend ^ "\n");
  output "else\n";
  output ("  QEND=" ^ protect boss_qend ^ "\n");
  output "fi\n\n";
  output "# Run with or without unquote filter\n";
  output "if [ $NOQUOTE -eq 1 ]; then\n";
  output (String.concat["  exec ", mosml, " -quietdec -P full -I ", sigobj,
                        " ", std_prelude, " $ARGS $QEND\n"]);
  output "else\n";
  output (String.concat["  exec ", qfilter, " | ", mosml, " -quietdec -P full -I ",
                        sigobj, " ", std_prelude, " ", qinit, " $ARGS $QEND\n"]);
  output "fi\n";
  TextIO.closeOut ostrm;
  mk_xable target
end
end (* local *)

fun bindstr s = s

end; (* struct *)
