# A dedicated workflow for building pull requests
name: docker-ci-for-pr

on:
  pull_request:
    branches:
      - "develop"

jobs:
  build-stdknl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: developers/docker-ci/Dockerfile
          push: false
          build-args: |
            SML=poly
            BUILDOPTS=--stdknl -j2 -t

  build-expk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: developers/docker-ci/Dockerfile
          push: false
          build-args: |
            SML=poly
            BUILDOPTS=--expk -j2 -t
