# A dedicated workflow for building pull requests
name: docker-ci-for-pr

on:
  pull_request:
    branches:
      - "develop"

jobs:
  build-stdknl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: developers/docker-ci/Dockerfile
          push: false
          build-args: |
            SML=poly
            Z3_VERSION=4.13.0
            CVC_VERSION=5
            CSDP_VERSION=1
            BUILDOPTS=--no-cache --stdknl -j4 -t

  build-expk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: developers/docker-ci/Dockerfile
          push: false
          build-args: |
            SML=poly
            Z3_VERSION=4.13.0
            CVC_VERSION=5
            CSDP_VERSION=1
            BUILDOPTS=--no-cache --expk -j4 -t

  build-mosml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: developers/docker-ci/Dockerfile
          push: false
          build-args: |
            SML=mosml
            BUILDOPTS=--no-cache --expk --seq=tools/sequences/upto-parallel -t

  build-otknl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: developers/docker-ci/Dockerfile
          push: false
          build-args: |
            SML=poly
            Z3_VERSION=4.13.0
            CVC_VERSION=5
            CSDP_VERSION=1
            BUILDOPTS=--no-cache --otknl -j2 --seq=tools/sequences/upto-parallel
